### PR TITLE
Update to swift 4.2, GoogleMap 2.7.0 RxSwift, RxCocoa 4.3.1

### PR DESCRIPTION
**Pull request by aksswami**
Update to latest swift version 4.2 and also Update dependencies to latest version
GoogleMaps 2.7.0
RxSwift 4.3.1
RxCocoa 4.3.1

Add .DS_Store to .gitignore
Resolve optional string warning

Bump version to 3.1.0

### CODE REVIEW

**Comment by freak4pc** [comment]
Hey @aksswami ! Thanks for this, looks great.

I actually think we could make most of the code backward compatible with Swift 4 since the changes are quite minimal. What do you think ?

**Comment by aksswami** [comment]
Yes, that's good idea. But I am not sure how to easily provide backward compatibility. If you guide me, I can make changes for that.

**Comment by freak4pc** [comment]
Here's an example you could go after, just this entire PR: 
https://github.com/RxSwiftCommunity/RxKeyboard/pull/73/files#diff-930b6ee73687964fabb525c330a64213R23

**Comment by aksswami** [comment]
Okay, will update this PR today with backward compatibility. Thanks for the pointer.

**Comment by aksswami** [comment]
PR updated as per your @freak4pc suggestions.

**Comment by freak4pc** [comment]
Thanks !

**Pull request merged**
