### PR TITLE
RxSwift (4.1.1) and RxCocoa (4.1.1)

### PR DESCRIPTION
**Pull request by MarsXan**
I Updated to RxCocoa (4.1.1) and RxSwift (4.1.1)

### CODE REVIEW

**Comment by freak4pc** [comment]
Hey MarsXan - I really appreciate your PR very very much, and hope to see more PRs from you :) 

There are a few problems with this specific PR:

1. It doesn't have **any** actual code changes whatsoever - the Swift 4 code works on 4.1 without this change
2. It just updates the Pod dependencies which isn't really something we'd necessarily want to do since it makes no difference for this specific library or the example project
3. You committed your AppCode folder which you usually shouldn't do

For this reasons, I think it's better to not merge this addition, hope its understandable, and again - I highly appreciated your effort and hope to see you push more PRs in the future :) 

If you think any of the points I wrote are wrong, feel free to comment and I can reopen this PR. 

Thanks!
Shai

**Comment by MarsXan** [comment]
@freak4pc 
Thanks for your Excellent Comment And your Excellent libraries
I forked your library because I got this error in Cocoapod then upgraded it to swift and cocoa 4.1
here is the Error : 
CocoaPods could not find compatible versions for pod "RxSwift":
  ```
In snapshot (Podfile.lock):
    RxSwift (= 4.1.2)

  In Podfile:
    RxCocoa was resolved to 4.1.2, which depends on
      RxSwift (~> 4.0)

    RxGoogleMaps was resolved to 2.1.1, which depends on
      RxSwift (~> 3.0.0-beta.2)

    RxSwift
```

screen shot 2018-02-13 at 12 18 23 pm

**Comment by freak4pc** [comment]
Hey @MarsXan - That's a great point! 

Do you mind trying changing the Podspec on your fork from `~> 4.0` to just `~> 4` and see if it solves it? 

https://github.com/RxSwiftCommunity/RxGoogleMaps/blob/master/RxGoogleMaps.podspec#L15

If yes, and you feel like pushing a new PR with just that change, I'd love to accept it !

**Comment by freak4pc** [comment]
You know what, I actually think that's not the problem at all :) 

The problem is that as of today the public Podspec is still old, since the original owner of this repo disappeared and is not pushing new specs. 

The easiest way to solve it is, in your Podfile do something like

```
pod 'RxGoogleMaps', git: 'https://github.com/RxSwiftCommunity/RxGoogleMaps', branch: 'master'
```

We're trying to fix these sort of issues in https://github.com/RxSwiftCommunity/contributors/issues/44

**Comment by freak4pc** [comment]
@MarsXan 3.0.0 was just pushed to CocoaPods and should work just fine !

**Pull request closed without merging**
