### PR TITLE
Update Google Maps SDK to 3.x

### PR DESCRIPTION
**Pull request by freak4pc**
My plan is to release 3.2.0 to support Xcode 10.1 with the new Google Maps SDK and then 4.0.0 to support Xcode 10.2 & Swift 5 with the new Google Maps SDK.

Any notes welcomed.

### CODE REVIEW

**Comment by freak4pc** [comment]
@GabrielAraujo care to review?

**Review by LucianoPAlmeida — APPROVED** [review]
LGTM 👍

**Comment by GabrielAraujo** [comment]
@freak4pc @LucianoPAlmeida did the work already, it's 👍 for me too!  =D

**Comment by freak4pc** [comment]
Thanks, both!

**Pull request merged**
